// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Table("AggregatedService")]
public partial class AggregatedService
{
    [Key]
    public int Id { get; set; }

    public DateOnly? lastModified { get; set; }

    public int lastModiFifiedBy { get; set; }
}