// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Keyless]
[Table("AggregatedServiceRelation")]
public partial class AggregatedServiceRelation
{
    public int? aggregatedServiceId { get; set; }

    public int? receiverServiceId { get; set; }

    public DateOnly? lastModified { get; set; }

    public int? lastModifiedBy { get; set; }

    [ForeignKey("aggregatedServiceId")]
    public virtual AggregatedService aggregatedService { get; set; }

    [ForeignKey("receiverServiceId")]
    public virtual ReceiverService receiverService { get; set; }
}