// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Table("Groupp")]
public partial class Groupp
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string name { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string contactName { get; set; }

    public int ownerGroupId { get; set; }

    public int ownerUddiBusinessId { get; set; }

    [InverseProperty("owneGroup")]
    public virtual ICollection<Participant> Participants { get; set; } = new List<Participant>();
}