// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Table("Participant")]
public partial class Participant
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string unitname { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string unitcvr { get; set; }

    public int? owneGroupId { get; set; }

    public int? ownerBusinessID { get; set; }

    public int? key { get; set; }

    public int? keyType { get; set; }

    [InverseProperty("ownerparticipant")]
    public virtual ICollection<ParticiPantBinding> ParticiPantBindings { get; set; } = new List<ParticiPantBinding>();

    [ForeignKey("owneGroupId")]
    [InverseProperty("Participants")]
    public virtual Groupp owneGroup { get; set; }
}