// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Table("Profiling")]
public partial class Profiling
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string profilName { get; set; }

    public int? businessId { get; set; }

    [InverseProperty("profiling")]
    public virtual ICollection<ReceiverService> ReceiverServices { get; set; } = new List<ReceiverService>();
}