// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Nxm_NRH_mgt.Models;

[Table("ServicE")]
public partial class ServicE
{
    [Key]
    public int id { get; set; }

    public int? networkTypeId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    public int? ownerBusinessId { get; set; }
}